// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, Start, Stop, Update, Validate, assert, async, getCorenovaID, getPromise, needle, putConfig, schema_SafeSearch, validate;

  validate = require('json-schema').validate;

  assert = require('assert');

  Promise = require('bluebird');

  async = require('async');

  needle = Promise.promisifyAll(require('needle'));

  schema_SafeSearch = require('./schema').SafeSearch;

  getPromise = function() {
    return new Promise(function(resolve, reject) {
      return resolve();
    });
  };

  Validate = function(config) {
    var checkschema;
    if (!config) {
      throw new Error("Validate SafeSearch - invalid input");
    }
    checkschema = validate(config, schema_SafeSearch);
    console.log('SafeSearch schema validate result: ', checkschema);
    if (!checkschema.valid) {
      throw new Error("SafeSearch schema check failed" + checkschema.valid);
      return false;
    } else {
      return true;
    }
  };

  getCorenovaID = function(baseUrl) {
    return needle.getAsync(baseUrl + "/corenova", {
      json: true
    }).then((function(_this) {
      return function(resp) {
        var corenovaResp;
        if (resp[0].statusCode !== 200) {
          throw new Error('invalidStatusCode');
        }
        corenovaResp = resp[0].body;
        console.log("corenovaID: ", corenovaResp[0].id);
        return corenovaResp[0].id;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  putConfig = function(baseUrl, id, config) {
    return needle.putAsync(baseUrl + ("/corenova/" + id + "/transform/include"), config, {
      json: true
    }).then((function(_this) {
      return function(resp) {
        if (resp[0].statusCode !== 200) {
          throw new Error('invalidStatusCode');
        }
        return config;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  Start = function(context) {
    if (!(context.bInstalledPackages && context.service.name && context.service.factoryConfig && context.service.factoryConfig.config.safesearch.enable)) {
      throw new Error('safesearch-storm.Start missingParams');
    }
    return getPromise().then((function(_this) {
      return function() {
        return Validate(context.service.factoryConfig.config.safesearch.urlfilter.config);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        return getCorenovaID(context.baseUrl);
      };
    })(this)).then((function(_this) {
      return function(corenovaID) {
        return putConfig(context.baseUrl, corenovaID, context.service.factoryConfig.config.safesearch.urlfilter.config);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        context.bFactoryPush = true;
        console.log("SafeSearch START response:\n " + JSON.stringify(context));
        return context;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  Update = function(context) {
    if (!(context.bInstalledPackages && context.service.name && context.service.policyConfig && context.service.policyConfig.safesearch.enable)) {
      throw new Error('safesearch-storm.update missingParams');
    }
    return getPromise().then((function(_this) {
      return function() {
        return Validate(context.service.policyConfig.safesearch.urlfilter.config);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        return getCorenovaID(context.baseUrl);
      };
    })(this)).then((function(_this) {
      return function(corenovaID) {
        return putConfig(context.baseUrl, corenovaID, context.service.policyConfig.safesearch.urlfilter.config);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        console.log("SafeSearch UPDATE response:\n " + JSON.stringify(resp));
        return context;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  Stop = function(context) {
    var config;
    if (!(context.bInstalledPackages && context.service.name && context.service.factoryConfig)) {
      throw new Error('safesearch-storm.Start missingParams');
    }
    config = {
      "HAVE_SAFESEARCH": false,
      "SAFESEARCH_POLICY": {
        "filename": "safesearch.policy",
        "encoding": "base64",
        "data": ""
      },
      "SAFESEARCH": false,
      "SAFESEARCH_RESPONSE": false
    };
    return getPromise().then((function(_this) {
      return function() {
        return Validate(config);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        return getCorenovaID(context.baseUrl);
      };
    })(this)).then((function(_this) {
      return function(corenovaID) {
        return putConfig(context.baseUrl, corenovaID, config);
      };
    })(this)).then((function(_this) {
      return function(resp) {
        console.log("SafeSearch STOP response:\n " + JSON.stringify(resp));
        return context;
      };
    })(this))["catch"]((function(_this) {
      return function(err) {
        throw err;
      };
    })(this));
  };

  module.exports.start = Start;

  module.exports.stop = Stop;

  module.exports.update = Update;

  module.exports.validate = Validate;

}).call(this);
